export const STORAGE_KEY = 'myrilo-theme';

export const FAILURE_LABELS = [
	'HALLUCINATION',
	'IRRELEVANCE',
	'REFUSAL',
	'FORMATTING_DRIFT',
	'GROUNDING_FAILURE',
	'SCORE_WITHOUT_EVIDENCE',
	'EVALUATOR_DISAGREEMENT',
] as const;
